source/tutorials/token_factory_1.md

how about that.
Still Highlighting to JavaScript?

modernized Tutorial contract

---

source/docs/contracts.md

Keystore
Random privateKey
Bit of layout

Docs for accounts

---

source/docs/index.md

Replace testrpc with ganache-cli

---

source/docs/create_project.md

Add template option

---

source/docs/embark_commands.md

Update docs to match https://github.com/embark-framework/embark/pull/862.

update docs re: 'new' help output

---

source/docs/contracts_configuration.md

add deployIf section

---

source/tutorials/token_factory_1.md

This makes it work and consistent with what we show below.

Fix balanceOf call signature

---

source/docs/create_project.md
source/docs/embark_commands.md

Revise `--template` related docs per https://github.com/embark-framework/embark/pull/903.

rev --template docs per revised implementation of the downloader

---

source/docs/contracts_configuration.md

Refs: https://github.com/embark-framework/embark/issues/938

contracts_configuration: Add documentation on deployment tracking.

---

source/docs/structure.md

Also ensuring they are linking to relevant docs that are mentioned.

docs(guides/app-structure): giving the structure docs a bit more love

---

source/docs/create_project.md
source/docs/structure.md

docs: add docs for --template option in demo command

---

source/docs/contracts_configuration.md

docs(smart_contracts/config): overhaul smart contract docs

---

source/docs/plugin_reference.md

I also removed the `embark` from the titles, so that the sidebar shows the actual function instead of being truncated

New console api

---

source/docs/blockchain_configuration.md

Related to https://github.com/embark-framework/embark/pull/1240

feat: add parity warning and auto cors doc

---

source/_data/sidebar.yml
themes/navy/languages/en.yml
themes/navy/layout/partial/sidebar.swig
themes/navy/source/css/_partial/sidebar.styl
themes/navy/source/js/search.js

Same version switcher, but for master
Once this is merged, we can deploy master and BOOM, we have a version switcher
The deplosy should be automatic for the develop branch and go to https://embark-site-develop.netlify.com/docs/

feat(site): add version switcher

---

source/_posts/2019-02-04-building-a-decentralized-reddit-with-embark-part-1.md
source/_posts/2019-02-11-building-a-decentralized-reddit-with-embark-part-2.md

This is now only part 2 of the tutorial

tutorial: add second part of tutorial series for building DReddit

---

source/_posts/2019-03-11-upgrading-to-embark-4.md

Lists the breaking changes and the new pipeline possibility

Add article on how to upgrade to embark 4

---

source/_posts/2019-03-11-upgrading-to-embark-4.md

Just adding the article to master too.

feat: add upgrade to embark 4 article in master

---

source/_data/plugins.yml

Update `embark-status` to `embark-status-plugin` and update URL to NPM repo.

fix(plugins): Update `embark-status` to `embark-status-plugin`

---

source/docs/contracts_configuration.md

**Only merge and release after https://github.com/embark-framework/embark/pull/1504 has been merged and release**

docs(contracts_configuration): add docs for logger dependency in deployment hooks

---

source/docs/configuration.md
source/docs/running_apps.md

Needs to be release when https://github.com/embark-framework/embark/pull/1511 has been released.

docs: add docs about reset configuration options
